name: secure_qr_verifier_windows
description: SecureQR verifier with Windows webcam and USB QR reader support
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  camera_windows: ^0.2.6+1
  zxing2: ^0.2.3
  image: ^4.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
