name: Build Windows Flutter App

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Add Windows platform folder if missing
        run: flutter create .

      - name: Build Windows release
        run: flutter build windows --release

      - name: Zip artifact
        run: powershell -Command "Compress-Archive -Path build\\windows\\runner\\Release\\* -DestinationPath build_windows_release.zip -Force"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build_windows_release.zip
