name: Build Windows Flutter App

on:
  workflow_dispatch:       # manual trigger button
  push:
    branches: [ master ]   # or main if your default branch is main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'   # Explicit stable version known to work
          channel: 'stable'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Zip build output
        run: powershell -Command "Compress-Archive -Path build\\windows\\runner\\Release\\* -DestinationPath build_windows_release.zip -Force"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build_windows_release.zip
