name: Build SecureQR (Windows + Web)

on:
  workflow_dispatch:   # manual trigger only

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Clean old builds
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure Windows platform folder exists
        run: flutter create --platforms=windows .

      # 🟦 Windows build
      - name: Build Windows release
        run: flutter build windows --release

      - name: Zip Windows build
        run: |
          $date = Get-Date -Format "yyyyMMdd_HHmm"
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath "SecureQR_Windows_$date.zip" -Force

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: SecureQR_Windows
          path: SecureQR_Windows_*.zip

      # 🌐 Web build
      - name: Build Web release
        run: flutter build web --release

      - name: Zip Web build
        run: |
          $date = Get-Date -Format "yyyyMMdd_HHmm"
          Compress-Archive -Path build\web\* -DestinationPath "SecureQR_Web_$date.zip" -Force

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: SecureQR_Web
          path: SecureQR_Web_*.zip
